file = {
    "cluster.lua",
    "cluster/auth.lua",
    "cluster/admin.lua",
    "cluster/rpc.lua",
    "cluster/pool.lua",
    "cluster/confapplier.lua",
    "cluster/test_helpers.lua",
    "cluster/test_helpers/cluster.lua",
    "cluster/test_helpers/server.lua",
    "cluster/service-registry.lua",
    "cluster/user-defined-role.lua",
}
topics = {
    "README.md",
    "CHANGELOG.md",
}
format = 'markdown'
