file = {
    "cartridge.lua",
    "cartridge/auth.lua",
    "cartridge/admin.lua",
    "cartridge/argparse.lua",
    "cartridge/rpc.lua",
    "cartridge/pool.lua",
    "cartridge/confapplier.lua",
    "cartridge/test-helpers.lua",
    "cartridge/test-helpers/cluster.lua",
    "cartridge/test-helpers/server.lua",
    "cartridge/remote-control.lua",
    "cartridge/service-registry.lua",
    "cartridge/user-defined-role.lua",
}
topics = {
    "README.md",
    "CHANGELOG.md",
}
format = 'markdown'
