/* APP */
export const APP_DID_MOUNT = 'APP_DID_MOUNT';

export const APP_DATA_REQUEST = 'APP_DATA_REQUEST';
export const APP_DATA_REQUEST_SUCCESS = 'APP_DATA_REQUEST_SUCCESS';
export const APP_DATA_REQUEST_ERROR = 'APP_DATA_REQUEST_ERROR';

export const APP_LOGIN_REQUEST = 'APP_LOGIN_REQUEST';
export const APP_LOGIN_REQUEST_SUCCESS = 'APP_LOGIN_REQUEST_SUCCESS';
export const APP_LOGIN_REQUEST_ERROR = 'APP_LOGIN_REQUEST_ERROR';

export const APP_LOGOUT_REQUEST = 'APP_LOGOUT_REQUEST';
export const APP_LOGOUT_REQUEST_SUCCESS = 'APP_LOGOUT_REQUEST_SUCCESS';
export const APP_LOGOUT_REQUEST_ERROR = 'APP_LOGOUT_REQUEST_ERROR';

export const APP_DENY_ANONYMOUS_REQUEST = 'APP_DENY_ANONYMOUS_REQUEST';
export const APP_DENY_ANONYMOUS_REQUEST_SUCCESS = 'APP_DENY_ANONYMOUS_REQUEST_SUCCESS';
export const APP_DENY_ANONYMOUS_REQUEST_ERROR = 'APP_DENY_ANONYMOUS_REQUEST_ERROR';

export const APP_ALLOW_ANONYMOUS_REQUEST = 'APP_ALLOW_ANONYMOUS_REQUEST';
export const APP_ALLOW_ANONYMOUS_REQUEST_SUCCESS = 'APP_ALLOW_ANONYMOUS_REQUEST_SUCCESS';
export const APP_ALLOW_ANONYMOUS_REQUEST_ERROR = 'APP_ALLOW_ANONYMOUS_REQUEST_ERROR';

export const APP_SERVER_CONSOLE_EVAL_STRING_REQUEST = 'APP_SERVER_CONSOLE_EVAL_STRING_REQUEST';
export const APP_SERVER_CONSOLE_EVAL_STRING_REQUEST_SUCCESS = 'APP_SERVER_CONSOLE_EVAL_STRING_REQUEST_SUCCESS';
export const APP_SERVER_CONSOLE_EVAL_STRING_REQUEST_ERROR = 'APP_SERVER_CONSOLE_EVAL_STRING_REQUEST_ERROR';

export const APP_SAVE_CONSOLE_STATE = 'APP_SAVE_CONSOLE_STATE';
export const APP_FORCE_LOGOUT = 'APP_FORCE_LOGOUT';

export const APP_CREATE_MESSAGE = 'APP_CREATE_MESSAGE';
export const APP_SET_MESSAGE_DONE = 'APP_SET_MESSAGE_DONE';

/* CLUSTER_PAGE */
export const CLUSTER_PAGE_DID_MOUNT = 'CLUSTER_PAGE_DID_MOUNT';

export const CLUSTER_PAGE_DATA_REQUEST = 'CLUSTER_PAGE_DATA_REQUEST';
export const CLUSTER_PAGE_DATA_REQUEST_SUCCESS = 'CLUSTER_PAGE_DATA_REQUEST_SUCCESS';
export const CLUSTER_PAGE_DATA_REQUEST_ERROR = 'CLUSTER_PAGE_DATA_REQUEST_ERROR';

export const CLUSTER_PAGE_REFRESH_LISTS_REQUEST = 'CLUSTER_PAGE_REFRESH_LISTS_REQUEST';
export const CLUSTER_PAGE_REFRESH_LISTS_REQUEST_SUCCESS = 'CLUSTER_PAGE_REFRESH_LISTS_REQUEST_SUCCESS';
export const CLUSTER_PAGE_REFRESH_LISTS_REQUEST_ERROR = 'CLUSTER_PAGE_REFRESH_LISTS_REQUEST_ERROR';

export const CLUSTER_PAGE_SERVER_LIST_ROW_SELECT = 'CLUSTER_PAGE_SERVER_LIST_ROW_SELECT';
export const CLUSTER_PAGE_SERVER_POPUP_CLOSE = 'CLUSTER_PAGE_SERVER_POPUP_CLOSE';

export const CLUSTER_PAGE_REPLICASET_LIST_ROW_SELECT = 'CLUSTER_PAGE_REPLICASET_LIST_ROW_SELECT';
export const CLUSTER_PAGE_REPLICASET_POPUP_CLOSE = 'CLUSTER_PAGE_REPLICASET_POPUP_CLOSE';

export const CLUSTER_PAGE_PROBE_SERVER_REQUEST = 'CLUSTER_PAGE_PROBE_SERVER_REQUEST';
export const CLUSTER_PAGE_PROBE_SERVER_REQUEST_SUCCESS = 'CLUSTER_PAGE_PROBE_SERVER_REQUEST_SUCCESS';
export const CLUSTER_PAGE_PROBE_SERVER_REQUEST_ERROR = 'CLUSTER_PAGE_PROBE_SERVER_REQUEST_ERROR';

export const CLUSTER_PAGE_JOIN_SERVER_REQUEST = 'CLUSTER_PAGE_JOIN_SERVER_REQUEST';
export const CLUSTER_PAGE_JOIN_SERVER_REQUEST_SUCCESS = 'CLUSTER_PAGE_JOIN_SERVER_REQUEST_SUCCESS';
export const CLUSTER_PAGE_JOIN_SERVER_REQUEST_ERROR = 'CLUSTER_PAGE_JOIN_SERVER_REQUEST_ERROR';

export const CLUSTER_PAGE_CREATE_REPLICASET_REQUEST = 'CLUSTER_PAGE_CREATE_REPLICASET_REQUEST';
export const CLUSTER_PAGE_CREATE_REPLICASET_REQUEST_SUCCESS = 'CLUSTER_PAGE_CREATE_REPLICASET_REQUEST_SUCCESS';
export const CLUSTER_PAGE_CREATE_REPLICASET_REQUEST_ERROR = 'CLUSTER_PAGE_CREATE_REPLICASET_REQUEST_ERROR';

export const CLUSTER_PAGE_EXPELL_SERVER_REQUEST = 'CLUSTER_PAGE_EXPELL_SERVER_REQUEST';
export const CLUSTER_PAGE_EXPELL_SERVER_REQUEST_SUCCESS = 'CLUSTER_PAGE_EXPELL_SERVER_REQUEST_SUCCESS';
export const CLUSTER_PAGE_EXPELL_SERVER_REQUEST_ERROR = 'CLUSTER_PAGE_EXPELL_SERVER_REQUEST_ERROR';

export const CLUSTER_PAGE_REPLICASET_EDIT_REQUEST = 'CLUSTER_PAGE_REPLICASET_EDIT_REQUEST';
export const CLUSTER_PAGE_REPLICASET_EDIT_REQUEST_SUCCESS = 'CLUSTER_PAGE_REPLICASET_EDIT_REQUEST_SUCCESS';
export const CLUSTER_PAGE_REPLICASET_EDIT_REQUEST_ERROR = 'CLUSTER_PAGE_REPLICASET_EDIT_REQUEST_ERROR';

export const CLUSTER_PAGE_UPLOAD_CONFIG_REQUEST = 'CLUSTER_PAGE_UPLOAD_CONFIG_REQUEST';
export const CLUSTER_PAGE_UPLOAD_CONFIG_REQUEST_SUCCESS = 'CLUSTER_PAGE_UPLOAD_CONFIG_REQUEST_SUCCESS';
export const CLUSTER_PAGE_UPLOAD_CONFIG_REQUEST_ERROR = 'CLUSTER_PAGE_UPLOAD_CONFIG_REQUEST_ERROR';

export const CLUSTER_PAGE_APPLY_TEST_CONFIG_REQUEST = 'CLUSTER_PAGE_APPLY_TEST_CONFIG_REQUEST';
export const CLUSTER_PAGE_APPLY_TEST_CONFIG_REQUEST_SUCCESS = 'CLUSTER_PAGE_APPLY_TEST_CONFIG_REQUEST_SUCCESS';
export const CLUSTER_PAGE_APPLY_TEST_CONFIG_REQUEST_ERROR = 'CLUSTER_PAGE_APPLY_TEST_CONFIG_REQUEST_ERROR';

export const CLUSTER_PAGE_STATE_RESET = 'CLUSTER_PAGE_STATE_RESET';
