name: Update translation sources

on:
  push:
    paths:
      - 'rst/**.rst'
      - 'rst/**.po'
    branches:
      - master
jobs:
  autocommit-pot-files:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup tarantool
      uses: tarantool/setup-tarantool@v3
      with:
        tarantool-version: '2.6'

    - name: Setup Python environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.0'

    - name: Setup Python requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r rst/requirements.txt

    - name: Create Makefile
      run: cmake .

    - name: Update pot files
      run: make update-pot

    - name: Push Pot-files to crowdin
      uses: crowdin/github-action@1.1.0
      with:
        upload_sources: true
        upload_translations: true
        import_eq_suggestions: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
